version: '3.7'

services:
    mongo:
        image: mongo
        restart: always
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${DATABASE_NAME}
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongo
        ports:
            - "8081:8081"
    spider:
        build: 
            context: ./rp_spider
            dockerfile: Dockerfile

    # frontend:
    #     build: ./react/Dockerfile

    # pipeline:
    #     build: ./pipeline/Dockerfile

    # api:
    #     build: ./api/Dockerfile